nohup python import.py /home/migration/LDAPcapture/device_child_0 >device_child_0.out &
nohup python import.py /home/migration/LDAPcapture/device_child_1 >device_child_1.out &
nohup python import.py /home/migration/LDAPcapture/device_child_2 >device_child_2.out &
nohup python import.py /home/migration/LDAPcapture/device_child_3 >device_child_3.out &
nohup python import.py /home/migration/LDAPcapture/device_child_4 >device_child_4.out &
nohup python import.py /home/migration/LDAPcapture/device_child_5 >device_child_5.out &
nohup python import.py /home/migration/LDAPcapture/device_child_6 >device_child_6.out &
nohup python import.py /home/migration/LDAPcapture/device_child_7 >device_child_7.out &
nohup python import.py /home/migration/LDAPcapture/device_child_8 >device_child_8.out &
nohup python import.py /home/migration/LDAPcapture/device_child_9 >device_child_9.out &
